# defalut port
server.port=8080

# Spring
spring.profiles.active=@spring.profiles.active@
spring.output.ansi.enabled=always

# AOP
aop.debug.enabled=true

# JPA
spring.jpa.open-in-view=true

# Spring async pool
spring.task.pool.corePoolSize=5
spring.task.pool.maxPoolSize=50
spring.task.pool.keepAliveSeconds=60
spring.task.pool.queueCapacity=10000
spring.task.pool.threadNamePrefix=NSMS-ASYNC-Thread-

# swagger
springdoc.swagger-ui.path=/demo-documentation
springdoc.api-docs.path=/demo-api-docs
springdoc.packages-to-scan=com.demo.controller
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true

# Upload Files Limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB